source 'https://svrgitpub.sdos.es/iOS/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def core_pods

    #Services
    pod 'SDOSPluggableApplicationDelegate'

    #Keyboard
    pod 'IQKeyboardManagerSwift'

    #Images
    pod 'Kingfisher'
    
    #WS
    pod 'SDOSAlamofire'
    
    #Database
    #pod 'RealmWrapper'
    
    #Architecture
    pod 'SDOSVIPER'
    pod 'PromiseKit'
	
    #Code Generation, dependency injection and environments variables
    pod 'SDOSEnvironment'
    pod 'SDOSSwinject'
    pod 'SwiftGen'
    
    #Animations and loaders
    pod 'SDOSHero'
    pod 'SDOSLoader'
    
    #Extensions
    pod 'SwifterSwift'
    
    #Debug
    pod 'SDOSFLEX', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
    
end

target :UnidadEditorialItunes do
	core_pods
end
